version: '3.5'  

services: 
    frontend: 
      image: frontend 
      ports: 
        - 5000:5000
      command: npm start
    backend:
      image: backend
      links:
        - redis:alpine
      ports:
        - 8000:8000
      environment:
        - REDIS=redis
      command: npm start
    redis: 
      image: redis:latest
      expose:
        - 6379
      ports:
        - 6379:6379