version: '3.5'  

services: 
    frontend: 
      image: frontend 
      ports: 
        - 5000:5000
      command: npm start
    backend:
      image: backend
      links: redis
      ports:
        - 8000:8000
      command: npm start


